### PR TITLE
Color keys in the hierarchical output uniformly

### PR DESCRIPTION
**Pull request by jtyr**
## WHAT

This PR is making the keys in hierarchical outputs (YAML, JSON, explain) to have the same color.

## WHY

Having all keys of the same color improves readability of the output.

### CODE REVIEW

**Comment by prune998** [comment]
Hey @jtyr  thanks for your PR.
I've been trying to understand what it changes but I wasn't able to see a difference with/without your patch... Am I missing something  ?

I tried using `kubecolor-jtyr get pods prometheus-prometheus-node-exporter-hbhf5 -o yaml --no-plain-hierarchy`

**Comment by jtyr** [comment]
The difference is as shown bellow (left with my patch, right without my patch):
image

**Comment by prune998** [comment]
Thanks for quick answer.

I actually cloned the `kubecolor` project into a new repo and applied a ton of patches, so I guess the output now changed slightly:
https://github.com/kubecolor/kubecolor

image

I guess it's still not on-par with your patch

**Comment by hidetatz** [comment]
Currently, I don't accept PRs which changes the color rules as it's completely personal preference and will lead us the endless discussion. Closing now

**Pull request closed without merging**
